import OpenAIProvider from '../OpenAIProvider.js';

// Mock fetch globally
global.fetch = jest.fn();

describe('OpenAIProvider', () => {
  let provider;

  beforeEach(() => {
    provider = new OpenAIProvider();
    fetch.mockClear();
  });

  describe('Configuration', () => {
    test('should configure with API key', async () => {
      await provider.configure({
        apiKey: 'test-api-key',
        model: 'gpt-4',
        temperature: 0.5,
        maxTokens: 1000
      });

      expect(provider.apiKey).toBe('test-api-key');
      expect(provider.model).toBe('gpt-4');
      expect(provider.temperature).toBe(0.5);
      expect(provider.maxTokens).toBe(1000);
    });

    test('should use default values when not provided', async () => {
      await provider.configure({ apiKey: 'test-key' });

      expect(provider.model).toBe('gpt-4');
      expect(provider.temperature).toBe(0.3);
      expect(provider.maxTokens).toBe(2000);
    });

    test('should throw error without API key', async () => {
      await expect(provider.configure({}))
        .rejects.toThrow('OpenAI API key is required');
    });
  });

  describe('Summary Generation', () => {
    beforeEach(async () => {
      await provider.configure({ apiKey: 'test-key' });
    });

    test('should generate summary successfully', async () => {
      const mockResponse = {
        choices: [{
          message: {
            content: 'This is a test summary of the meeting.'
          }
        }]
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse)
      });

      const transcript = 'Test meeting transcript';
      const prompt = 'Summarize this meeting';

      const result = await provider.generateSummary(transcript, prompt);

      expect(result).toBe('This is a test summary of the meeting.');
      expect(fetch).toHaveBeenCalledWith(
        'https://api.openai.com/v1/chat/completions',
        expect.objectContaining({
          method: 'POST',
          headers: {
            'Authorization': 'Bearer test-key',
            'Content-Type': 'application/json'
          }
        })
      );
    });

    test('should handle API errors', async () => {
      fetch.mockResolvedValueOnce({
        ok: false,
        status: 401,
        statusText: 'Unauthorized',
        json: () => Promise.resolve({
          error: { message: 'Invalid API key' }
        })
      });

      await expect(provider.generateSummary('transcript', 'prompt'))
        .rejects.toThrow('OpenAI API error: 401 - Invalid API key');
    });

    test('should handle empty response', async () => {
      fetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ choices: [] })
      });

      await expect(provider.generateSummary('transcript', 'prompt'))
        .rejects.toThrow('No summary generated by OpenAI');
    });

    test('should handle network errors', async () => {
      fetch.mockRejectedValueOnce(new Error('Network error'));

      await expect(provider.generateSummary('transcript', 'prompt'))
        .rejects.toThrow('OpenAI summary generation failed: Network error');
    });

    test('should send correct request format', async () => {
      const mockResponse = {
        choices: [{ message: { content: 'Test summary' } }]
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse)
      });

      await provider.generateSummary('Test transcript', 'Test prompt');

      const requestBody = JSON.parse(fetch.mock.calls[0][1].body);
      
      expect(requestBody.model).toBe('gpt-4');
      expect(requestBody.messages).toHaveLength(2);
      expect(requestBody.messages[0].role).toBe('system');
      expect(requestBody.messages[0].content).toBe('Test prompt');
      expect(requestBody.messages[1].role).toBe('user');
      expect(requestBody.messages[1].content).toContain('Test transcript');
      expect(requestBody.temperature).toBe(0.3);
      expect(requestBody.max_tokens).toBe(2000);
    });
  });

  describe('Connection Testing', () => {
    beforeEach(async () => {
      await provider.configure({ apiKey: 'test-key' });
    });

    test('should test connection successfully', async () => {
      fetch.mockResolvedValueOnce({ ok: true });

      const result = await provider.testConnection();

      expect(result).toBe(true);
      expect(fetch).toHaveBeenCalledWith(
        'https://api.openai.com/v1/models',
        expect.objectContaining({
          method: 'GET',
          headers: {
            'Authorization': 'Bearer test-key',
            'Content-Type': 'application/json'
          }
        })
      );
    });

    test('should handle connection failure', async () => {
      fetch.mockResolvedValueOnce({ ok: false });

      const result = await provider.testConnection();

      expect(result).toBe(false);
    });

    test('should handle network error during connection test', async () => {
      fetch.mockRejectedValueOnce(new Error('Network error'));

      const result = await provider.testConnection();

      expect(result).toBe(false);
    });
  });

  describe('Model Management', () => {
    beforeEach(async () => {
      await provider.configure({ apiKey: 'test-key' });
    });

    test('should get available models', async () => {
      const mockModels = {
        data: [
          { id: 'gpt-4', object: 'model' },
          { id: 'gpt-3.5-turbo', object: 'model' },
          { id: 'text-davinci-003', object: 'model' }
        ]
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockModels)
      });

      const models = await provider.getAvailableModels();

      expect(models).toHaveLength(2); // Only GPT models
      expect(models[0].id).toBe('gpt-3.5-turbo');
      expect(models[1].id).toBe('gpt-4');
    });

    test('should return default models on API failure', async () => {
      fetch.mockRejectedValueOnce(new Error('API error'));

      const models = await provider.getAvailableModels();

      expect(models).toHaveLength(3);
      expect(models.map(m => m.id)).toContain('gpt-4');
      expect(models.map(m => m.id)).toContain('gpt-3.5-turbo');
    });

    test('should get correct context length for models', () => {
      expect(provider.getModelContextLength('gpt-4')).toBe(8192);
      expect(provider.getModelContextLength('gpt-4-turbo-preview')).toBe(128000);
      expect(provider.getModelContextLength('gpt-3.5-turbo')).toBe(4096);
      expect(provider.getModelContextLength('unknown-model')).toBe(4096);
    });
  });

  describe('Token Management', () => {
    test('should estimate token count', () => {
      const text = 'This is a test message with some words.';
      const tokens = provider.estimateTokenCount(text);
      
      expect(tokens).toBeGreaterThan(0);
      expect(tokens).toBe(Math.ceil(text.length / 4));
    });

    test('should check if content fits in context', () => {
      provider.model = 'gpt-4'; // 8192 tokens
      provider.maxTokens = 1000;

      const shortText = 'Short text';
      const longText = 'x'.repeat(30000); // Very long text

      expect(provider.fitsInContext(shortText, 'prompt')).toBe(true);
      expect(provider.fitsInContext(longText, 'prompt')).toBe(false);
    });

    test('should truncate transcript when too long', () => {
      provider.model = 'gpt-4';
      provider.maxTokens = 1000;

      const longTranscript = 'x'.repeat(50000);
      const prompt = 'Short prompt';

      const truncated = provider.truncateTranscript(longTranscript, prompt);

      expect(truncated.length).toBeLessThan(longTranscript.length);
      expect(truncated).toContain('[... transcript truncated for length ...]');
    });

    test('should not truncate short transcript', () => {
      const shortTranscript = 'This is a short transcript.';
      const prompt = 'Short prompt';

      const result = provider.truncateTranscript(shortTranscript, prompt);

      expect(result).toBe(shortTranscript);
    });
  });

  describe('Provider Information', () => {
    test('should return provider info', () => {
      const info = provider.getProviderInfo();

      expect(info.name).toBe('OpenAI');
      expect(info.id).toBe('openai_gpt');
      expect(info.requiresApiKey).toBe(true);
      expect(info.models).toContain('gpt-4');
      expect(info.features).toBeInstanceOf(Array);
    });
  });
});