/**
 * Teams Chat Service - Handles sending transcripts and summaries to Teams chat
 * Supports message formatting, splitting, and alternative delivery methods
 */

class TeamsChatService {
  constructor() {
    this.teamsAdapter = null;
    this.maxMessageLength = 4000; // Teams message limit
    this.maxMessagesPerBatch = 5; // Limit to avoid rate limiting
    this.retryAttempts = 3;
    this.retryDelay = 1000; // 1 second
  }

  /**
   * Set Teams adapter instance
   * @param {TeamsAdapter} teamsAdapter - Teams adapter instance
   */
  setTeamsAdapter(teamsAdapter) {
    this.teamsAdapter = teamsAdapter;
  }

  /**
   * Check if chat integration is available and user has permissions
   * @returns {Promise<Object>} Permission status and capabilities
   */
  async checkChatPermissions() {
    try {
      if (!this.teamsAdapter) {
        return {
          hasPermission: false,
          error: 'Teams adapter not initialized',
          capabilities: {}
        };
      }

      // Check if we're in a meeting context
      const meetingInfo = this.teamsAdapter.getMeetingInfo();
      if (!meetingInfo || meetingInfo.state !== 'active') {
        return {
          hasPermission: false,
          error: 'Not in an active meeting',
          capabilities: {}
        };
      }

      // Check if user is host (required for sending messages)
      const isHost = this.teamsAdapter.getHostStatus();
      if (!isHost) {
        return {
          hasPermission: false,
          error: 'Only meeting host can send messages to chat',
          capabilities: {}
        };
      }

      // Get platform capabilities
      const capabilities = this.teamsAdapter.getPlatformCapabilities();
      
      return {
        hasPermission: true,
        capabilities: capabilities,
        meetingId: meetingInfo.id,
        context: meetingInfo.context
      };
    } catch (error) {
      console.error('Error checking chat permissions:', error);
      return {
        hasPermission: false,
        error: error.message,
        capabilities: {}
      };
    }
  }

  /**
   * Format transcript for Teams chat display
   * @param {Object} transcript - Meeting transcript object
   * @param {Object} options - Formatting options
   * @returns {string} Formatted transcript text
   */
  formatTranscriptForChat(transcript, options = {}) {
    try {
      const {
        includeTimestamps = false,
        includeSpeakerLabels = true,
        includeHeader = true,
        includeFooter = true,
        maxSegments = null
      } = options;

      let formattedText = '';

      // Add header
      if (includeHeader) {
        const meetingTitle = transcript.meetingTitle || 'Teams Meeting';
        const startTime = transcript.startTime ? 
          new Date(transcript.startTime).toLocaleString() : 
          new Date().toLocaleString();
        
        formattedText += `📝 **Meeting Transcript**\n`;
        formattedText += `**Meeting:** ${meetingTitle}\n`;
        formattedText += `**Date:** ${startTime}\n`;
        formattedText += `**Participants:** ${this.formatParticipantsList(transcript.speakers)}\n\n`;
        formattedText += `---\n\n`;
      }

      // Process transcript segments
      const segments = transcript.segments || [];
      const segmentsToProcess = maxSegments ? segments.slice(0, maxSegments) : segments;
      
      let currentSpeaker = null;
      let speakerText = '';

      for (const segment of segmentsToProcess) {
        const speakerId = segment.speakerId || 'Unknown Speaker';
        
        // Group consecutive segments from same speaker
        if (currentSpeaker !== speakerId) {
          // Add previous speaker's text
          if (currentSpeaker && speakerText.trim()) {
            formattedText += this.formatSpeakerSegment(
              currentSpeaker, 
              speakerText.trim(), 
              includeTimestamps ? segment.startTime : null
            );
          }
          
          // Start new speaker
          currentSpeaker = speakerId;
          speakerText = segment.text;
        } else {
          // Continue with same speaker
          speakerText += ' ' + segment.text;
        }
      }

      // Add final speaker's text
      if (currentSpeaker && speakerText.trim()) {
        formattedText += this.formatSpeakerSegment(currentSpeaker, speakerText.trim());
      }

      // Add footer
      if (includeFooter) {
        const duration = this.calculateTranscriptDuration(transcript);
        const segmentCount = segments.length;
        
        formattedText += `\n---\n\n`;
        formattedText += `📊 **Summary:** ${segmentCount} segments, ${duration} minutes\n`;
        formattedText += `🤖 Generated by Meeting Transcription Plugin`;
      }

      return formattedText;
    } catch (error) {
      console.error('Error formatting transcript:', error);
      return `Error formatting transcript: ${error.message}`;
    }
  }

  /**
   * Format individual speaker segment
   * @param {string} speakerId - Speaker identifier
   * @param {string} text - Speaker's text
   * @param {number} timestamp - Optional timestamp
   * @returns {string} Formatted speaker segment
   */
  formatSpeakerSegment(speakerId, text, timestamp = null) {
    let segment = '';
    
    // Add timestamp if provided
    if (timestamp) {
      const time = new Date(timestamp).toLocaleTimeString();
      segment += `[${time}] `;
    }
    
    // Add speaker label
    segment += `**${speakerId}:** ${text}\n\n`;
    
    return segment;
  }

  /**
   * Format participants list
   * @param {Array} speakers - List of speakers
   * @returns {string} Formatted participants string
   */
  formatParticipantsList(speakers) {
    if (!speakers || speakers.length === 0) {
      return 'No speakers identified';
    }
    
    return speakers.join(', ');
  }

  /**
   * Calculate transcript duration
   * @param {Object} transcript - Transcript object
   * @returns {number} Duration in minutes
   */
  calculateTranscriptDuration(transcript) {
    if (!transcript.segments || transcript.segments.length === 0) {
      return 0;
    }

    const firstSegment = transcript.segments[0];
    const lastSegment = transcript.segments[transcript.segments.length - 1];
    
    if (firstSegment.startTime !== undefined && lastSegment.endTime !== undefined) {
      return Math.round((lastSegment.endTime - firstSegment.startTime) / 60000);
    }

    return 0;
  }

  /**
   * Split long message into multiple parts
   * @param {string} message - Message to split
   * @param {number} maxLength - Maximum length per message
   * @returns {Array} Array of message parts
   */
  splitLongMessage(message, maxLength = null) {
    const limit = maxLength || this.maxMessageLength;
    
    if (message.length <= limit) {
      return [message];
    }

    const parts = [];
    let currentPart = '';
    const lines = message.split('\n');
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const lineWithNewline = i === 0 ? line : '\n' + line;
      
      // Check if adding this line would exceed the limit
      if (currentPart.length + lineWithNewline.length > limit) {
        // If current part is not empty, save it
        if (currentPart.trim()) {
          parts.push(currentPart.trim());
          currentPart = '';
        }
        
        // If single line is too long, split it by sentences
        if (line.length > limit) {
          const sentenceParts = this.splitBySentences(line, limit);
          parts.push(...sentenceParts);
        } else {
          currentPart = line;
        }
      } else {
        currentPart += lineWithNewline;
      }
    }
    
    // Add remaining part
    if (currentPart.trim()) {
      parts.push(currentPart.trim());
    }

    // Add part numbers if multiple parts
    if (parts.length > 1) {
      return parts.map((part, index) => 
        `**Part ${index + 1}/${parts.length}**\n\n${part}`
      );
    }

    return parts;
  }

  /**
   * Split text by sentences when lines are too long
   * @param {string} text - Text to split
   * @param {number} maxLength - Maximum length per part
   * @returns {Array} Array of text parts
   */
  splitBySentences(text, maxLength) {
    const sentences = text.split(/(?<=[.!?])\s+/);
    const parts = [];
    let currentPart = '';

    for (const sentence of sentences) {
      if (currentPart.length + sentence.length + 1 > maxLength) {
        if (currentPart.trim()) {
          parts.push(currentPart.trim());
          currentPart = '';
        }
        
        // If single sentence is still too long, split by words
        if (sentence.length > maxLength) {
          const wordParts = this.splitByWords(sentence, maxLength);
          parts.push(...wordParts);
        } else {
          currentPart = sentence;
        }
      } else {
        currentPart += (currentPart ? ' ' : '') + sentence;
      }
    }

    if (currentPart.trim()) {
      parts.push(currentPart.trim());
    }

    return parts;
  }

  /**
   * Split text by words when sentences are too long
   * @param {string} text - Text to split
   * @param {number} maxLength - Maximum length per part
   * @returns {Array} Array of text parts
   */
  splitByWords(text, maxLength) {
    const words = text.split(' ');
    const parts = [];
    let currentPart = '';

    for (const word of words) {
      if (currentPart.length + word.length + 1 > maxLength) {
        if (currentPart.trim()) {
          parts.push(currentPart.trim());
          currentPart = '';
        }
        
        // If single word is too long, truncate it
        if (word.length > maxLength) {
          parts.push(word.substring(0, maxLength - 3) + '...');
        } else {
          currentPart = word;
        }
      } else {
        currentPart += (currentPart ? ' ' : '') + word;
      }
    }

    if (currentPart.trim()) {
      parts.push(currentPart.trim());
    }

    return parts;
  }

  /**
   * Send transcript to Teams chat
   * @param {Object} transcript - Meeting transcript
   * @param {Object} options - Send options
   * @returns {Promise<Object>} Send result
   */
  async sendTranscriptToChat(transcript, options = {}) {
    try {
      // Check if transcript is provided
      if (!transcript) {
        return {
          success: false,
          error: 'No transcript provided',
          alternativeMethod: this.getAlternativeDeliveryMethod({}, 'transcript')
        };
      }

      // Check permissions first
      const permissionCheck = await this.checkChatPermissions();
      if (!permissionCheck.hasPermission) {
        return {
          success: false,
          error: permissionCheck.error,
          alternativeMethod: this.getAlternativeDeliveryMethod(transcript)
        };
      }

      // Format transcript
      const formattedTranscript = this.formatTranscriptForChat(transcript, options);
      
      // Split into multiple messages if needed
      const messageParts = this.splitLongMessage(formattedTranscript);
      
      // Send messages with delay between them
      const results = [];
      for (let i = 0; i < messageParts.length; i++) {
        const part = messageParts[i];
        
        // Add delay between messages to avoid rate limiting
        if (i > 0) {
          await this.delay(this.retryDelay);
        }
        
        const result = await this.sendMessageWithRetry(part);
        results.push(result);
        
        // Stop if any message fails
        if (!result.success) {
          break;
        }
      }

      // Check if all messages were sent successfully
      const failedMessages = results.filter(r => !r.success);
      if (failedMessages.length > 0) {
        return {
          success: false,
          error: `Failed to send ${failedMessages.length} of ${results.length} messages`,
          partialSuccess: results.some(r => r.success),
          results: results,
          alternativeMethod: this.getAlternativeDeliveryMethod(transcript)
        };
      }

      return {
        success: true,
        messagesSent: results.length,
        results: results
      };

    } catch (error) {
      console.error('Error sending transcript to chat:', error);
      return {
        success: false,
        error: error.message,
        alternativeMethod: this.getAlternativeDeliveryMethod(transcript)
      };
    }
  }

  /**
   * Send summary to Teams chat
   * @param {Object} summary - Meeting summary
   * @param {Object} options - Send options
   * @returns {Promise<Object>} Send result
   */
  async sendSummaryToChat(summary, options = {}) {
    try {
      // Check if summary is provided
      if (!summary) {
        return {
          success: false,
          error: 'No summary provided',
          alternativeMethod: this.getAlternativeDeliveryMethod({}, 'summary')
        };
      }

      // Check permissions first
      const permissionCheck = await this.checkChatPermissions();
      if (!permissionCheck.hasPermission) {
        return {
          success: false,
          error: permissionCheck.error,
          alternativeMethod: this.getAlternativeDeliveryMethod(summary, 'summary')
        };
      }

      // Format summary for chat
      const formattedSummary = this.formatSummaryForChat(summary, options);
      
      // Split into multiple messages if needed
      const messageParts = this.splitLongMessage(formattedSummary);
      
      // Send messages
      const results = [];
      for (let i = 0; i < messageParts.length; i++) {
        const part = messageParts[i];
        
        if (i > 0) {
          await this.delay(this.retryDelay);
        }
        
        const result = await this.sendMessageWithRetry(part);
        results.push(result);
        
        if (!result.success) {
          break;
        }
      }

      const failedMessages = results.filter(r => !r.success);
      if (failedMessages.length > 0) {
        return {
          success: false,
          error: `Failed to send ${failedMessages.length} of ${results.length} summary messages`,
          partialSuccess: results.some(r => r.success),
          results: results,
          alternativeMethod: this.getAlternativeDeliveryMethod(summary, 'summary')
        };
      }

      return {
        success: true,
        messagesSent: results.length,
        results: results
      };

    } catch (error) {
      console.error('Error sending summary to chat:', error);
      return {
        success: false,
        error: error.message,
        alternativeMethod: this.getAlternativeDeliveryMethod(summary, 'summary')
      };
    }
  }

  /**
   * Format summary for Teams chat display
   * @param {Object} summary - Meeting summary object
   * @param {Object} options - Formatting options
   * @returns {string} Formatted summary text
   */
  formatSummaryForChat(summary, options = {}) {
    try {
      const {
        includeMetadata = true,
        includeAgendaItems = true,
        includeActionItems = true,
        includeDecisions = true
      } = options;

      let formattedText = '';

      // Header
      formattedText += `🎯 **Meeting Summary**\n\n`;

      // Metadata
      if (includeMetadata && summary.metadata) {
        const generatedAt = new Date(summary.metadata.generatedAt).toLocaleString();
        formattedText += `**Generated:** ${generatedAt}\n`;
        formattedText += `**Duration:** ${summary.metadata.meetingDuration || 'N/A'} minutes\n`;
        formattedText += `**Participants:** ${summary.participants?.join(', ') || 'N/A'}\n\n`;
      }

      // Key Points
      if (summary.keyPoints && summary.keyPoints.length > 0) {
        formattedText += `**📋 Key Discussion Points:**\n`;
        summary.keyPoints.forEach(point => {
          formattedText += `• ${point}\n`;
        });
        formattedText += `\n`;
      }

      // Decisions
      if (includeDecisions && summary.decisions && summary.decisions.length > 0) {
        formattedText += `**✅ Decisions Made:**\n`;
        summary.decisions.forEach(decision => {
          formattedText += `• ${decision}\n`;
        });
        formattedText += `\n`;
      }

      // Action Items
      if (includeActionItems && summary.actionItems && summary.actionItems.length > 0) {
        formattedText += `**📝 Action Items:**\n`;
        summary.actionItems.forEach(item => {
          let actionText = `• ${item.task || item}`;
          if (item.assignee) {
            actionText += ` (${item.assignee})`;
          }
          if (item.dueDate) {
            actionText += ` - Due: ${item.dueDate}`;
          }
          formattedText += `${actionText}\n`;
        });
        formattedText += `\n`;
      }

      // Agenda Items
      if (includeAgendaItems && summary.agendaItems && summary.agendaItems.length > 0) {
        formattedText += `**📅 Agenda Coverage:**\n`;
        summary.agendaItems.forEach(item => {
          const status = item.discussed ? '✅' : '❌';
          formattedText += `${status} ${item.title}\n`;
          if (item.summary && item.discussed) {
            formattedText += `   ${item.summary}\n`;
          }
        });
        formattedText += `\n`;
      }

      // Next Steps
      if (summary.nextSteps && summary.nextSteps.length > 0) {
        formattedText += `**🚀 Next Steps:**\n`;
        summary.nextSteps.forEach(step => {
          formattedText += `• ${step}\n`;
        });
        formattedText += `\n`;
      }

      // Footer
      formattedText += `---\n`;
      formattedText += `🤖 AI-generated summary using ${summary.metadata?.provider || 'AI'} service`;

      return formattedText;
    } catch (error) {
      console.error('Error formatting summary:', error);
      return `Error formatting summary: ${error.message}`;
    }
  }

  /**
   * Send message with retry logic
   * @param {string} message - Message to send
   * @returns {Promise<Object>} Send result
   */
  async sendMessageWithRetry(message) {
    let lastError = null;
    
    for (let attempt = 1; attempt <= this.retryAttempts; attempt++) {
      try {
        console.log(`Sending message (attempt ${attempt}/${this.retryAttempts})`);
        
        // Use Teams adapter to send message
        const result = await this.teamsAdapter.sendMessageToChat(message);
        
        if (result.success) {
          return {
            success: true,
            attempt: attempt,
            messageLength: message.length
          };
        } else {
          lastError = result.error || 'Unknown error';
          console.warn(`Message send attempt ${attempt} failed:`, lastError);
        }
        
      } catch (error) {
        lastError = error.message;
        console.warn(`Message send attempt ${attempt} failed:`, error);
      }
      
      // Wait before retry (except on last attempt)
      if (attempt < this.retryAttempts) {
        await this.delay(this.retryDelay * attempt);
      }
    }
    
    return {
      success: false,
      error: lastError,
      attempts: this.retryAttempts
    };
  }

  /**
   * Get alternative delivery method when chat is not available
   * @param {Object} content - Content to deliver (transcript or summary)
   * @param {string} type - Content type ('transcript' or 'summary')
   * @returns {Object} Alternative delivery options
   */
  getAlternativeDeliveryMethod(content, type = 'transcript') {
    const alternatives = [];

    // Local download option
    alternatives.push({
      method: 'download',
      title: `Download ${type} as file`,
      description: `Save the ${type} as a text file to your computer`,
      action: () => this.downloadAsFile(content, type),
      available: true
    });

    // Copy to clipboard option
    alternatives.push({
      method: 'clipboard',
      title: `Copy ${type} to clipboard`,
      description: `Copy the formatted ${type} to your clipboard`,
      action: () => this.copyToClipboard(content, type),
      available: navigator.clipboard !== undefined
    });

    // Email option (if available)
    alternatives.push({
      method: 'email',
      title: `Send ${type} via email`,
      description: `Open your email client with the ${type} pre-filled`,
      action: () => this.sendViaEmail(content, type),
      available: true
    });

    // Local storage option
    alternatives.push({
      method: 'storage',
      title: `Save ${type} locally`,
      description: `Store the ${type} in browser local storage for later access`,
      action: () => this.saveToLocalStorage(content, type),
      available: true
    });

    return {
      reason: 'Teams chat integration not available',
      alternatives: alternatives.filter(alt => alt.available)
    };
  }

  /**
   * Download content as file
   * @param {Object} content - Content to download
   * @param {string} type - Content type
   */
  downloadAsFile(content, type) {
    try {
      const formattedContent = type === 'summary' ? 
        this.formatSummaryForChat(content) : 
        this.formatTranscriptForChat(content);
      
      const blob = new Blob([formattedContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      
      const a = document.createElement('a');
      a.href = url;
      a.download = `meeting-${type}-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      
      URL.revokeObjectURL(url);
      
      return { success: true, method: 'download' };
    } catch (error) {
      console.error('Error downloading file:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Copy content to clipboard
   * @param {Object} content - Content to copy
   * @param {string} type - Content type
   */
  async copyToClipboard(content, type) {
    try {
      const formattedContent = type === 'summary' ? 
        this.formatSummaryForChat(content) : 
        this.formatTranscriptForChat(content);
      
      await navigator.clipboard.writeText(formattedContent);
      
      return { success: true, method: 'clipboard' };
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Send content via email
   * @param {Object} content - Content to send
   * @param {string} type - Content type
   */
  sendViaEmail(content, type) {
    try {
      const formattedContent = type === 'summary' ? 
        this.formatSummaryForChat(content) : 
        this.formatTranscriptForChat(content);
      
      const subject = `Meeting ${type} - ${new Date().toLocaleDateString()}`;
      const body = encodeURIComponent(formattedContent);
      
      const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${body}`;
      window.open(mailtoUrl);
      
      return { success: true, method: 'email' };
    } catch (error) {
      console.error('Error opening email client:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Save content to local storage
   * @param {Object} content - Content to save
   * @param {string} type - Content type
   */
  saveToLocalStorage(content, type) {
    try {
      const key = `meeting-${type}-${Date.now()}`;
      const data = {
        type: type,
        content: content,
        savedAt: new Date().toISOString(),
        meetingId: content.meetingId || 'unknown'
      };
      
      localStorage.setItem(key, JSON.stringify(data));
      
      return { success: true, method: 'storage', key: key };
    } catch (error) {
      console.error('Error saving to local storage:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Utility function to add delay
   * @param {number} ms - Milliseconds to delay
   * @returns {Promise} Promise that resolves after delay
   */
  delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Get chat service status
   * @returns {Object} Service status information
   */
  getStatus() {
    return {
      initialized: !!this.teamsAdapter,
      maxMessageLength: this.maxMessageLength,
      maxMessagesPerBatch: this.maxMessagesPerBatch,
      retryAttempts: this.retryAttempts,
      retryDelay: this.retryDelay
    };
  }

  /**
   * Update service configuration
   * @param {Object} config - Configuration options
   */
  updateConfig(config) {
    if (config.maxMessageLength) {
      this.maxMessageLength = config.maxMessageLength;
    }
    if (config.maxMessagesPerBatch) {
      this.maxMessagesPerBatch = config.maxMessagesPerBatch;
    }
    if (config.retryAttempts) {
      this.retryAttempts = config.retryAttempts;
    }
    if (config.retryDelay) {
      this.retryDelay = config.retryDelay;
    }
  }
}

export default TeamsChatService;