/**
 * Azure OpenAI Provider - Integration with Azure OpenAI Service for summary generation
 */

class AzureOpenAIProvider {
  constructor() {
    this.apiKey = null;
    this.endpoint = null;
    this.deploymentName = null;
    this.apiVersion = '2024-02-15-preview';
    this.model = 'gpt-4';
    this.temperature = 0.3;
    this.maxTokens = 2000;
  }

  /**
   * Configure the Azure OpenAI provider
   * @param {Object} config - Configuration options
   */
  async configure(config) {
    this.apiKey = config.apiKey;
    this.endpoint = config.endpoint;
    this.deploymentName = config.deploymentName || config.model || 'gpt-4';
    this.model = config.model || 'gpt-4';
    this.temperature = config.temperature || 0.3;
    this.maxTokens = config.maxTokens || 2000;
    
    if (config.apiVersion) {
      this.apiVersion = config.apiVersion;
    }

    if (!this.apiKey) {
      throw new Error('Azure OpenAI API key is required');
    }

    if (!this.endpoint) {
      throw new Error('Azure OpenAI endpoint is required');
    }

    // Ensure endpoint format is correct
    this.endpoint = this.normalizeEndpoint(this.endpoint);
  }

  /**
   * Normalize Azure endpoint URL
   * @param {string} endpoint - Raw endpoint URL
   * @returns {string} Normalized endpoint
   */
  normalizeEndpoint(endpoint) {
    // Remove trailing slash
    endpoint = endpoint.replace(/\/$/, '');
    
    // Ensure it starts with https://
    if (!endpoint.startsWith('https://')) {
      endpoint = `https://${endpoint}`;
    }

    // Ensure it ends with .openai.azure.com if it's just a resource name
    if (!endpoint.includes('.openai.azure.com')) {
      endpoint = `${endpoint}.openai.azure.com`;
    }

    return endpoint;
  }

  /**
   * Generate summary using Azure OpenAI
   * @param {string} transcript - Formatted transcript text
   * @param {string} prompt - System prompt for summary generation
   * @returns {Promise<string>} Generated summary
   */
  async generateSummary(transcript, prompt) {
    try {
      const messages = [
        {
          role: 'system',
          content: prompt
        },
        {
          role: 'user',
          content: `Please summarize the following meeting transcript:\n\n${transcript}`
        }
      ];

      const url = `${this.endpoint}/openai/deployments/${this.deploymentName}/chat/completions?api-version=${this.apiVersion}`;

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'api-key': this.apiKey,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          messages: messages,
          temperature: this.temperature,
          max_tokens: this.maxTokens,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0,
          stream: false
        })
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(`Azure OpenAI API error: ${response.status} - ${errorData.error?.message || response.statusText}`);
      }

      const data = await response.json();
      
      if (!data.choices || data.choices.length === 0) {
        throw new Error('No summary generated by Azure OpenAI');
      }

      const summary = data.choices[0].message?.content;
      if (!summary) {
        throw new Error('Empty summary received from Azure OpenAI');
      }

      return summary.trim();
    } catch (error) {
      console.error('Azure OpenAI summary generation error:', error);
      throw new Error(`Azure OpenAI summary generation failed: ${error.message}`);
    }
  }

  /**
   * Test connection to Azure OpenAI API
   * @returns {Promise<boolean>} True if connection successful
   */
  async testConnection() {
    try {
      const url = `${this.endpoint}/openai/deployments?api-version=${this.apiVersion}`;
      
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'api-key': this.apiKey,
          'Content-Type': 'application/json'
        }
      });

      return response.ok;
    } catch (error) {
      console.error('Azure OpenAI connection test failed:', error);
      return false;
    }
  }

  /**
   * Get available deployments
   * @returns {Promise<Array>} List of available deployments
   */
  async getAvailableDeployments() {
    try {
      const url = `${this.endpoint}/openai/deployments?api-version=${this.apiVersion}`;
      
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'api-key': this.apiKey,
          'Content-Type': 'application/json'
        }
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch deployments: ${response.statusText}`);
      }

      const data = await response.json();
      
      return data.data?.map(deployment => ({
        id: deployment.id,
        name: deployment.id,
        model: deployment.model,
        status: deployment.status,
        createdAt: deployment.created_at,
        contextLength: this.getModelContextLength(deployment.model)
      })) || [];
    } catch (error) {
      console.error('Error fetching Azure OpenAI deployments:', error);
      // Return empty array if API call fails
      return [];
    }
  }

  /**
   * Get context length for a model
   * @param {string} modelId - Model identifier
   * @returns {number} Context length in tokens
   */
  getModelContextLength(modelId) {
    const contextLengths = {
      'gpt-4': 8192,
      'gpt-4-32k': 32768,
      'gpt-4-turbo': 128000,
      'gpt-4-turbo-preview': 128000,
      'gpt-35-turbo': 4096,
      'gpt-35-turbo-16k': 16384,
      'gpt-3.5-turbo': 4096,
      'gpt-3.5-turbo-16k': 16384
    };

    // Handle Azure naming conventions
    const normalizedModel = modelId.toLowerCase().replace(/[_-]/g, '-');
    return contextLengths[normalizedModel] || contextLengths[modelId] || 4096;
  }

  /**
   * Estimate token count for text
   * @param {string} text - Text to count tokens for
   * @returns {number} Estimated token count
   */
  estimateTokenCount(text) {
    // Rough estimation: 1 token ≈ 4 characters for English text
    return Math.ceil(text.length / 4);
  }

  /**
   * Check if transcript fits within model context
   * @param {string} transcript - Transcript text
   * @param {string} prompt - System prompt
   * @returns {boolean} True if it fits
   */
  fitsInContext(transcript, prompt) {
    const transcriptTokens = this.estimateTokenCount(transcript);
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const totalTokens = transcriptTokens + promptTokens + responseTokens;
    
    const contextLength = this.getModelContextLength(this.model);
    return totalTokens <= contextLength * 0.9; // Leave 10% buffer
  }

  /**
   * Truncate transcript to fit within context window
   * @param {string} transcript - Original transcript
   * @param {string} prompt - System prompt
   * @returns {string} Truncated transcript
   */
  truncateTranscript(transcript, prompt) {
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const contextLength = this.getModelContextLength(this.model);
    
    const availableTokens = contextLength - promptTokens - responseTokens - 100; // Buffer
    const maxCharacters = availableTokens * 4; // Convert back to characters
    
    if (transcript.length <= maxCharacters) {
      return transcript;
    }

    // Truncate from the middle to preserve beginning and end
    const keepStart = Math.floor(maxCharacters * 0.4);
    const keepEnd = Math.floor(maxCharacters * 0.4);
    
    const start = transcript.substring(0, keepStart);
    const end = transcript.substring(transcript.length - keepEnd);
    
    return `${start}\n\n[... transcript truncated for length ...]\n\n${end}`;
  }

  /**
   * Parse Azure endpoint to extract resource name
   * @param {string} endpoint - Azure endpoint URL
   * @returns {string} Resource name
   */
  parseResourceName(endpoint) {
    try {
      const url = new URL(endpoint);
      const hostname = url.hostname;
      
      // Extract resource name from hostname like "myresource.openai.azure.com"
      const match = hostname.match(/^([^.]+)\.openai\.azure\.com$/);
      return match ? match[1] : 'unknown';
    } catch (error) {
      return 'unknown';
    }
  }

  /**
   * Validate Azure configuration
   * @returns {Object} Validation result
   */
  validateConfiguration() {
    const errors = [];
    
    if (!this.apiKey) {
      errors.push('API key is required');
    }
    
    if (!this.endpoint) {
      errors.push('Endpoint is required');
    } else {
      try {
        new URL(this.endpoint);
      } catch (error) {
        errors.push('Invalid endpoint URL format');
      }
    }
    
    if (!this.deploymentName) {
      errors.push('Deployment name is required');
    }

    return {
      isValid: errors.length === 0,
      errors: errors
    };
  }

  /**
   * Get provider information
   * @returns {Object} Provider details
   */
  getProviderInfo() {
    return {
      name: 'Azure OpenAI',
      id: 'azure_openai',
      description: 'Microsoft Azure OpenAI Service for enterprise-grade AI',
      website: 'https://azure.microsoft.com/en-us/products/cognitive-services/openai-service',
      models: [
        'gpt-4',
        'gpt-4-32k',
        'gpt-4-turbo',
        'gpt-35-turbo',
        'gpt-35-turbo-16k'
      ],
      features: [
        'Enterprise security and compliance',
        'Private network support',
        'Data residency options',
        'SLA guarantees',
        'Integration with Azure services'
      ],
      pricing: 'Pay-per-token with Azure billing',
      requiresApiKey: true,
      requiresEndpoint: true,
      requiresDeployment: true
    };
  }

  /**
   * Get setup instructions for Azure OpenAI
   * @returns {Object} Setup instructions
   */
  getSetupInstructions() {
    return {
      steps: [
        'Create an Azure OpenAI resource in the Azure portal',
        'Deploy a GPT model (e.g., gpt-4) in Azure OpenAI Studio',
        'Copy the endpoint URL from the resource overview',
        'Copy the API key from the Keys and Endpoint section',
        'Note the deployment name you created for the model'
      ],
      requiredFields: [
        {
          name: 'endpoint',
          label: 'Endpoint URL',
          placeholder: 'https://your-resource.openai.azure.com',
          description: 'Your Azure OpenAI resource endpoint'
        },
        {
          name: 'apiKey',
          label: 'API Key',
          placeholder: 'Your Azure OpenAI API key',
          description: 'API key from your Azure OpenAI resource',
          type: 'password'
        },
        {
          name: 'deploymentName',
          label: 'Deployment Name',
          placeholder: 'gpt-4',
          description: 'Name of your model deployment'
        }
      ]
    };
  }
}

export default AzureOpenAIProvider;