/**
 * Claude Provider - Integration with Anthropic Claude models for summary generation
 */

class ClaudeProvider {
  constructor() {
    this.apiKey = null;
    this.baseURL = 'https://api.anthropic.com/v1';
    this.model = 'claude-3-sonnet-20240229';
    this.temperature = 0.3;
    this.maxTokens = 2000;
    this.anthropicVersion = '2023-06-01';
  }

  /**
   * Configure the Claude provider
   * @param {Object} config - Configuration options
   */
  async configure(config) {
    this.apiKey = config.apiKey;
    this.model = config.model || 'claude-3-sonnet-20240229';
    this.temperature = config.temperature || 0.3;
    this.maxTokens = config.maxTokens || 2000;
    
    if (config.baseURL) {
      this.baseURL = config.baseURL;
    }

    if (config.anthropicVersion) {
      this.anthropicVersion = config.anthropicVersion;
    }

    if (!this.apiKey) {
      throw new Error('Claude API key is required');
    }
  }

  /**
   * Generate summary using Claude
   * @param {string} transcript - Formatted transcript text
   * @param {string} prompt - System prompt for summary generation
   * @returns {Promise<string>} Generated summary
   */
  async generateSummary(transcript, prompt) {
    try {
      const messages = [
        {
          role: 'user',
          content: `${prompt}\n\nPlease summarize the following meeting transcript:\n\n${transcript}`
        }
      ];

      const response = await fetch(`${this.baseURL}/messages`, {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': this.anthropicVersion,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: this.model,
          messages: messages,
          max_tokens: this.maxTokens,
          temperature: this.temperature,
          system: 'You are an expert meeting summarizer. Provide clear, structured summaries that capture key points, decisions, and action items.'
        })
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(`Claude API error: ${response.status} - ${errorData.error?.message || response.statusText}`);
      }

      const data = await response.json();
      
      if (!data.content || data.content.length === 0) {
        throw new Error('No summary generated by Claude');
      }

      const summary = data.content[0]?.text;
      if (!summary) {
        throw new Error('Empty summary received from Claude');
      }

      return summary.trim();
    } catch (error) {
      console.error('Claude summary generation error:', error);
      throw new Error(`Claude summary generation failed: ${error.message}`);
    }
  }

  /**
   * Test connection to Claude API
   * @returns {Promise<boolean>} True if connection successful
   */
  async testConnection() {
    try {
      // Claude doesn't have a simple endpoint to test, so we'll make a minimal request
      const response = await fetch(`${this.baseURL}/messages`, {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': this.anthropicVersion,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: this.model,
          messages: [
            {
              role: 'user',
              content: 'Hello'
            }
          ],
          max_tokens: 10
        })
      });

      return response.ok;
    } catch (error) {
      console.error('Claude connection test failed:', error);
      return false;
    }
  }

  /**
   * Get available models
   * @returns {Promise<Array>} List of available models
   */
  async getAvailableModels() {
    // Claude doesn't have a models endpoint, so return known models
    return [
      {
        id: 'claude-3-opus-20240229',
        name: 'Claude 3 Opus',
        contextLength: 200000,
        description: 'Most capable model for complex tasks'
      },
      {
        id: 'claude-3-sonnet-20240229',
        name: 'Claude 3 Sonnet',
        contextLength: 200000,
        description: 'Balanced performance and speed'
      },
      {
        id: 'claude-3-haiku-20240307',
        name: 'Claude 3 Haiku',
        contextLength: 200000,
        description: 'Fastest model for simple tasks'
      },
      {
        id: 'claude-2.1',
        name: 'Claude 2.1',
        contextLength: 200000,
        description: 'Previous generation model'
      },
      {
        id: 'claude-2.0',
        name: 'Claude 2.0',
        contextLength: 100000,
        description: 'Previous generation model'
      }
    ];
  }

  /**
   * Get context length for a model
   * @param {string} modelId - Model identifier
   * @returns {number} Context length in tokens
   */
  getModelContextLength(modelId) {
    const contextLengths = {
      'claude-3-opus-20240229': 200000,
      'claude-3-sonnet-20240229': 200000,
      'claude-3-haiku-20240307': 200000,
      'claude-2.1': 200000,
      'claude-2.0': 100000,
      'claude-instant-1.2': 100000
    };

    return contextLengths[modelId] || 100000;
  }

  /**
   * Estimate token count for text
   * @param {string} text - Text to count tokens for
   * @returns {number} Estimated token count
   */
  estimateTokenCount(text) {
    // Claude uses similar tokenization to GPT models
    // Rough estimation: 1 token ≈ 4 characters for English text
    return Math.ceil(text.length / 4);
  }

  /**
   * Check if transcript fits within model context
   * @param {string} transcript - Transcript text
   * @param {string} prompt - System prompt
   * @returns {boolean} True if it fits
   */
  fitsInContext(transcript, prompt) {
    const transcriptTokens = this.estimateTokenCount(transcript);
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const totalTokens = transcriptTokens + promptTokens + responseTokens;
    
    const contextLength = this.getModelContextLength(this.model);
    return totalTokens <= contextLength * 0.9; // Leave 10% buffer
  }

  /**
   * Truncate transcript to fit within context window
   * @param {string} transcript - Original transcript
   * @param {string} prompt - System prompt
   * @returns {string} Truncated transcript
   */
  truncateTranscript(transcript, prompt) {
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const contextLength = this.getModelContextLength(this.model);
    
    const availableTokens = contextLength - promptTokens - responseTokens - 1000; // Buffer
    const maxCharacters = availableTokens * 4; // Convert back to characters
    
    if (transcript.length <= maxCharacters) {
      return transcript;
    }

    // Truncate from the middle to preserve beginning and end
    const keepStart = Math.floor(maxCharacters * 0.4);
    const keepEnd = Math.floor(maxCharacters * 0.4);
    
    const start = transcript.substring(0, keepStart);
    const end = transcript.substring(transcript.length - keepEnd);
    
    return `${start}\n\n[... transcript truncated for length ...]\n\n${end}`;
  }

  /**
   * Format prompt for Claude's specific requirements
   * @param {string} systemPrompt - System prompt
   * @param {string} userPrompt - User prompt
   * @returns {string} Formatted prompt
   */
  formatPrompt(systemPrompt, userPrompt) {
    // Claude works better with clear instructions in the user message
    return `${systemPrompt}\n\n${userPrompt}`;
  }

  /**
   * Handle Claude-specific response formatting
   * @param {string} response - Raw Claude response
   * @returns {string} Formatted response
   */
  formatResponse(response) {
    // Claude responses are generally well-formatted, but we can clean up if needed
    return response
      .trim()
      .replace(/\n{3,}/g, '\n\n') // Remove excessive line breaks
      .replace(/^\s*Summary:\s*/i, ''); // Remove redundant "Summary:" prefix
  }

  /**
   * Get provider information
   * @returns {Object} Provider details
   */
  getProviderInfo() {
    return {
      name: 'Anthropic Claude',
      id: 'claude',
      description: 'Anthropic Claude models for thoughtful and nuanced text generation',
      website: 'https://anthropic.com',
      models: [
        'claude-3-opus-20240229',
        'claude-3-sonnet-20240229',
        'claude-3-haiku-20240307',
        'claude-2.1',
        'claude-2.0'
      ],
      features: [
        'Large context windows (200K tokens)',
        'Thoughtful analysis',
        'Strong reasoning capabilities',
        'Constitutional AI training'
      ],
      pricing: 'Pay-per-token',
      requiresApiKey: true
    };
  }

  /**
   * Get model-specific recommendations
   * @param {number} transcriptLength - Length of transcript in characters
   * @returns {Object} Model recommendation
   */
  getModelRecommendation(transcriptLength) {
    const tokenCount = this.estimateTokenCount(transcriptLength);
    
    if (tokenCount > 150000) {
      return {
        model: 'claude-3-opus-20240229',
        reason: 'Large transcript requires most capable model'
      };
    } else if (tokenCount > 50000) {
      return {
        model: 'claude-3-sonnet-20240229',
        reason: 'Medium transcript, balanced performance'
      };
    } else {
      return {
        model: 'claude-3-haiku-20240307',
        reason: 'Small transcript, fast processing'
      };
    }
  }
}

export default ClaudeProvider;