/**
 * OpenAI Provider - Integration with OpenAI GPT models for summary generation
 */

class OpenAIProvider {
  constructor() {
    this.apiKey = null;
    this.baseURL = 'https://api.openai.com/v1';
    this.model = 'gpt-4';
    this.temperature = 0.3;
    this.maxTokens = 2000;
  }

  /**
   * Configure the OpenAI provider
   * @param {Object} config - Configuration options
   */
  async configure(config) {
    this.apiKey = config.apiKey;
    this.model = config.model || 'gpt-4';
    this.temperature = config.temperature || 0.3;
    this.maxTokens = config.maxTokens || 2000;
    
    if (config.baseURL) {
      this.baseURL = config.baseURL;
    }

    if (!this.apiKey) {
      throw new Error('OpenAI API key is required');
    }
  }

  /**
   * Generate summary using OpenAI GPT
   * @param {string} transcript - Formatted transcript text
   * @param {string} prompt - System prompt for summary generation
   * @returns {Promise<string>} Generated summary
   */
  async generateSummary(transcript, prompt) {
    try {
      const messages = [
        {
          role: 'system',
          content: prompt
        },
        {
          role: 'user',
          content: `Please summarize the following meeting transcript:\n\n${transcript}`
        }
      ];

      const response = await fetch(`${this.baseURL}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: this.model,
          messages: messages,
          temperature: this.temperature,
          max_tokens: this.maxTokens,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0
        })
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(`OpenAI API error: ${response.status} - ${errorData.error?.message || response.statusText}`);
      }

      const data = await response.json();
      
      if (!data.choices || data.choices.length === 0) {
        throw new Error('No summary generated by OpenAI');
      }

      const summary = data.choices[0].message?.content;
      if (!summary) {
        throw new Error('Empty summary received from OpenAI');
      }

      return summary.trim();
    } catch (error) {
      console.error('OpenAI summary generation error:', error);
      throw new Error(`OpenAI summary generation failed: ${error.message}`);
    }
  }

  /**
   * Test connection to OpenAI API
   * @returns {Promise<boolean>} True if connection successful
   */
  async testConnection() {
    try {
      const response = await fetch(`${this.baseURL}/models`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      return response.ok;
    } catch (error) {
      console.error('OpenAI connection test failed:', error);
      return false;
    }
  }

  /**
   * Get available models
   * @returns {Promise<Array>} List of available models
   */
  async getAvailableModels() {
    try {
      const response = await fetch(`${this.baseURL}/models`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch models: ${response.statusText}`);
      }

      const data = await response.json();
      
      // Filter for GPT models suitable for text generation
      const gptModels = data.data
        .filter(model => model.id.includes('gpt'))
        .map(model => ({
          id: model.id,
          name: model.id,
          contextLength: this.getModelContextLength(model.id)
        }))
        .sort((a, b) => a.name.localeCompare(b.name));

      return gptModels;
    } catch (error) {
      console.error('Error fetching OpenAI models:', error);
      // Return default models if API call fails
      return [
        { id: 'gpt-4', name: 'GPT-4', contextLength: 8192 },
        { id: 'gpt-4-turbo-preview', name: 'GPT-4 Turbo', contextLength: 128000 },
        { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', contextLength: 4096 }
      ];
    }
  }

  /**
   * Get context length for a model
   * @param {string} modelId - Model identifier
   * @returns {number} Context length in tokens
   */
  getModelContextLength(modelId) {
    const contextLengths = {
      'gpt-4': 8192,
      'gpt-4-turbo-preview': 128000,
      'gpt-4-0125-preview': 128000,
      'gpt-4-1106-preview': 128000,
      'gpt-3.5-turbo': 4096,
      'gpt-3.5-turbo-16k': 16384,
      'gpt-3.5-turbo-1106': 16385
    };

    return contextLengths[modelId] || 4096;
  }

  /**
   * Estimate token count for text
   * @param {string} text - Text to count tokens for
   * @returns {number} Estimated token count
   */
  estimateTokenCount(text) {
    // Rough estimation: 1 token ≈ 4 characters for English text
    return Math.ceil(text.length / 4);
  }

  /**
   * Check if transcript fits within model context
   * @param {string} transcript - Transcript text
   * @param {string} prompt - System prompt
   * @returns {boolean} True if it fits
   */
  fitsInContext(transcript, prompt) {
    const transcriptTokens = this.estimateTokenCount(transcript);
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const totalTokens = transcriptTokens + promptTokens + responseTokens;
    
    const contextLength = this.getModelContextLength(this.model);
    return totalTokens <= contextLength * 0.9; // Leave 10% buffer
  }

  /**
   * Truncate transcript to fit within context window
   * @param {string} transcript - Original transcript
   * @param {string} prompt - System prompt
   * @returns {string} Truncated transcript
   */
  truncateTranscript(transcript, prompt) {
    const promptTokens = this.estimateTokenCount(prompt);
    const responseTokens = this.maxTokens;
    const contextLength = this.getModelContextLength(this.model);
    
    const availableTokens = contextLength - promptTokens - responseTokens - 100; // Buffer
    const maxCharacters = availableTokens * 4; // Convert back to characters
    
    if (transcript.length <= maxCharacters) {
      return transcript;
    }

    // Truncate from the middle to preserve beginning and end
    const keepStart = Math.floor(maxCharacters * 0.4);
    const keepEnd = Math.floor(maxCharacters * 0.4);
    
    const start = transcript.substring(0, keepStart);
    const end = transcript.substring(transcript.length - keepEnd);
    
    return `${start}\n\n[... transcript truncated for length ...]\n\n${end}`;
  }

  /**
   * Get provider information
   * @returns {Object} Provider details
   */
  getProviderInfo() {
    return {
      name: 'OpenAI',
      id: 'openai_gpt',
      description: 'OpenAI GPT models for high-quality text generation',
      website: 'https://openai.com',
      models: [
        'gpt-4',
        'gpt-4-turbo-preview',
        'gpt-3.5-turbo'
      ],
      features: [
        'High-quality summaries',
        'Multiple model options',
        'Structured output',
        'Large context windows'
      ],
      pricing: 'Pay-per-token',
      requiresApiKey: true
    };
  }
}

export default OpenAIProvider;